### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by RightChain** [rspatial/terra#742] opened 2022-08-03 17:40 UTC
I run this package on r 3.6.3. This was an error in my docker build 4 days ago.

```[0m[91mError in parse(outFile) :
/tmp/RtmpkPZc6C/R.INSTALL1af2169d8a6/terra/R/zonal.R:72:42: unexpected input
71: r <- !relate(x, z, "disjoint")
72: i <- apply(r, 1, \
^
[0m[91mERROR: unable to collate and parse R files for package ‘terra’
```

I'm receiving the same install error on my local machine from within RStudio (R 3.6.3) while trying to compile from source:
```
Error in parse(outFile) : 
  C:/Users/trvss/AppData/Local/Temp/RtmpeYR3A8/R.INSTALLa534253e6346/terra/R/zonal.R:72:42: unexpected input
71:                         r <- !relate(x, z, "disjoint")
72:                         i <- apply(r, 1, \
                                             ^
ERROR: unable to collate and parse R files for package 'terra'
```

Note these installs are from the CRAN version. using `install.packages('terra')`

**Comment by rhijmans** [comment] 2022-08-03 18:28
duplicate of #725. Should be fixed sometime next week. For now, you can use the dev version, the previous release, or a more recent version of R.

**Closed by rhijmans** 2022-08-03 18:28 UTC
