### ISSUE TITLE
focalCpp produces incorrect result for large window sizes

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#519] opened 2022-01-31 16:35 UTC
When running `focalCpp` I am getting odd results at larger window sizes. I've included an example below where the code appears to run fine for 3x3 and 7x7, but for 25x25 something wonky is happening. This is likely related to (or the same as) rspatial/terra#479, but this occurs on Windows (have not tested it on another OS), while the other example only seemed to happen on Linux.

```
#Windows 10, 16GB RAM
#R version 4.0.4
library(Rcpp) #‘1.0.7’
library(terra) #‘1.5.17’


#Fit a Quadratic Surface to a focal window using OLS
cppFunction(depends = "RcppArmadillo", 'NumericMatrix C_OLSQuad(NumericVector z, NumericMatrix X, size_t ni, size_t nw) {
  
  size_t nlyr = X.ncol(); //Number of layers
  NumericMatrix out(ni, nlyr);
  out.fill(NA_REAL);
  colnames(out)= CharacterVector::create("a", "b", "c", "d", "e", "f");
  
  for (size_t i=0; i<ni; i++) {
    size_t start = i*nw;
    size_t end = start+nw-1;
    NumericVector zw = z[Rcpp::Range(start,end)]; //Current window of elevation values
    LogicalVector NA_idx = is_na(zw);
    if((is_true(any(NA_idx)))) {} else {
      NumericMatrix Z(zw.length(),1, zw.begin()); //Current window of elevation values as a 1 column matrix
      out(i, _) =  Rcpp::as<Rcpp::NumericVector>(wrap(solve(as<arma::mat>(X),as<arma::mat>(Z)))); //OLS regression coefficients
    }}
  return out;
}')

#Set up a Matrix of explanatory variables (centered xy position in the focal window)
create_Xmat<- function(r,w){
  x<- as.vector(t(matrix(data = seq(from = (-xres(r) * floor(w[2]/2)), to = (xres(r) * floor(w[2]/2)), length.out = w[2]), nrow = w[1], ncol=w[2], byrow=TRUE)))
  y<- as.vector(t(matrix(data = seq(from = (yres(r) * floor(w[1]/2)), to = (-yres(r) * floor(w[1]/2)), length.out = w[1]), nrow = w[1], ncol=w[2])))
  X<- cbind(x^2,y^2, x*y, x, y, 1) # Z = ax^2+by^2+cxy+dx+ey+f
  colnames(X)<- NULL
  return(X)
  }


#Create Data
r<- rast(nrow = 5005, ncol= 4893, crs="EPSG:32620", extent= c(164751.39956803, 409401.39956803, 4833140.707, 5083390.707))
set.seed(5)
values(r)<- rnorm(n = ncell(r), mean = -50, sd = 5)
r[,1:1000]<- NA
r[,3000:5005]<- NA
plot(r)
```
![r_plot](https://user-images.githubusercontent.com/28163862/151833905-7e349f6b-baa7-4576-8577-d113e7f90694.png)

```
#3x3 Window
X3<- create_Xmat(r,w=c(3,3))
params_3X3<- terra::focalCpp(r, w=c(3,3), fun = C_OLSQuad, X= X3, fillvalue=NA)
plot(params_3X3)
```
![params_3x3](https://user-images.githubusercontent.com/28163862/151833946-26be5544-545c-471f-8787-3ee90b87a051.png)

```
#7x7 Window
X7<- create_Xmat(r,w=c(7,7))
params_7X7<- terra::focalCpp(r, w=c(7,7), fun = C_OLSQuad, X= X7, fillvalue=NA)
plot(params_7X7)
```
![params_7x7](https://user-images.githubusercontent.com/28163862/151833988-d3046185-15eb-4a2a-9e85-7bb3f9ef7676.png)

```
#25x25 Window
X25<- create_Xmat(r,w=c(25,25))
params_25X25<- terra::focalCpp(r, w=c(25,25), fun = C_OLSQuad, X= X25, fillvalue=NA)
plot(params_25X25)
```
![params_25x25](https://user-images.githubusercontent.com/28163862/151834025-04366aa1-292e-4c5d-b4f0-2e0ed37952b5.png)

**Comment by Hallo951** [comment] 2022-01-31 17:02
I once had something similar while parallel predicting the result of a random forest model with very large data. There, the plot looked almost exactly as fragmented. When I predicted it without using the parallel option, the result was fine. Unfortunately I did not find a solution for this but maybe my observation helps a little bit to find the error.

**Comment by rhijmans** [comment] 2022-02-01 23:16
I cannot reproduce this. Can you confirm that this also happens with a much simpler cpp function?


```
library(terra)
library(Rcpp)

cppFunction( 
	'NumericVector fsum(NumericVector x, size_t ni, size_t nw) {
		NumericVector out(ni);
		for (size_t i=0; i<ni; i++) {
			size_t start = i * nw;
			double v=0;
			for (size_t j=start; j<(start+nw); j++) {
				v += x[j];
			}
			out[i] = v;
		}		
		return out;
	}'
)


r<- rast(nrow = 5005, ncol= 4893, crs="EPSG:32620", extent= c(164751.39956803, 409401.39956803, 4833140.707, 5083390.707))
set.seed(5)
values(r) <- rnorm(n = ncell(r), mean = -50, sd = 5)
r[,1:1000] <- NA
r[,3000:5005] <- NA
plot(r)

#terraOptions(maxmem=10)
p25 <- terra::focalCpp(r, w=25, fun=fsum)
plot(p25)
```

**Comment by rhijmans** [comment] 2022-02-02 00:49
@Hallo951 : I doubt that was the same problem. I looked at `predict` with `cores > 1` and found that the output was garbled if the number of predicted variables was > 1. That happens, for example, when using RF with `type=prob`. That is now fixed.

**Comment by ailich** [comment] 2022-02-02 15:50
@rhijmans, here is a simpler function that returns 6 values just based on summing values in the window. The small windows appear to work fine, but it breaks down for me at 19x19 (though a different run it broke down at 17).

```
library(terra)
library(Rcpp)

cppFunction('NumericMatrix C_sum2(NumericVector z, size_t ni, size_t nw) {
  
  size_t nlyr = 6; //Number of layers
  NumericMatrix out(ni, nlyr);
  out.fill(NA_REAL);

  for (size_t i=0; i<ni; i++) {
    size_t start = i*nw;
    size_t end = start+nw-1;
    NumericVector zw = z[Rcpp::Range(start,end)]; //Current window of values
    out(i, 0) =  zw[0]+zw[1];
    out(i, 1) =  zw[1]+zw[2];
    out(i, 2) =  zw[2]+zw[3];
    out(i, 3) =  zw[3]+zw[4];
    out(i, 4) =  zw[4]+zw[5];
    out(i, 5) =  zw[5]+zw[6];
    }
  return out;
}')

#Create Data
r<- rast(nrow = 5005, ncol= 4893, crs="EPSG:32620", extent= c(164751.39956803, 409401.39956803, 4833140.707, 5083390.707))
set.seed(5)
values(r)<- rnorm(n = ncell(r), mean = -50, sd = 5)
r[,1:1000]<- NA
r[,3000:5005]<- NA

v3x3<- terra::focalCpp(r, w=c(3,3), fun = C_sum2, fillvalue=NA)

v15x15<- terra::focalCpp(r, w=c(15,15), fun = C_sum2, fillvalue=NA)

v17x17<- terra::focalCpp(r, w=c(17,17), fun = C_sum2, fillvalue=NA)

v19x19<- terra::focalCpp(r, w=c(19,19), fun = C_sum2, fillvalue=NA)

v21x21<- terra::focalCpp(r, w=c(21,21), fun = C_sum2, fillvalue=NA)

v25x25<- terra::focalCpp(r, w=c(25,25), fun = C_sum2, fillvalue=NA)

first_layers<- c(r, v3x3[[1]], v15x15[[1]], v17x17[[1]], v19x19[[1]], v21x21[[1]], v25x25[[1]])
names(first_layers)<- c("original", "w3", "w15", "w17", "w19", "w21", "w25")
plot(first_layers)
```
![first_layers](https://user-images.githubusercontent.com/28163862/152187624-7b0b27af-f29a-4428-9f9d-10930e4c7fa6.png)

**Comment by ailich** [comment] 2022-02-02 16:13
@rhijmans, I can also reproduce it with a minor alteration to the `fsum` function you provided. The version you wrote works; however, if I make a slight modification so that it returns multiple values rather than a single value I run into the same issue.

```
library(terra)
library(Rcpp)

#Minor edit to fsum to make it return 6 layers (all identical)
cppFunction( 
  'NumericVector fsum2(NumericVector x, size_t ni, size_t nw) {
		NumericMatrix out(ni, 6);
		for (size_t i=0; i<ni; i++) {
			size_t start = i * nw;
			double v=0;
			for (size_t j=start; j<(start+nw); j++) {
				v += x[j];
			}
			out(i, _) = rep(v, 6);
		}		
		return out;
	}'
)


r<- rast(nrow = 5005, ncol= 4893, crs="EPSG:32620", extent= c(164751.39956803, 409401.39956803, 4833140.707, 5083390.707))
set.seed(5)
values(r) <- rnorm(n = ncell(r), mean = -50, sd = 5)
r[,1:1000] <- NA
r[,3000:5005] <- NA

p25 <- terra::focalCpp(r, w=25, fun=fsum2)
plot(p25)
```

![p25](https://user-images.githubusercontent.com/28163862/152192117-f3399eed-5577-47fc-be82-d87c0b6bfa60.png)

**Comment by ailich** [comment] 2022-02-02 20:34
@rhijmans, I can also reproduce this with multiband outputs for the normal `focal` function as opposed to `focalCpp`. I don't run into the issue using much smaller rasters so (e.g. 100 rows by 50 columns), so it seems to be related to the size of the raster, the window size, and the number of bands in the output layer.

```
library(terra)
#Create Data
r<- rast(nrow = 5005, ncol= 4893, crs="EPSG:32620", extent= c(164751.39956803, 409401.39956803, 4833140.707, 5083390.707))
set.seed(5)
values(r)<- rnorm(n = ncell(r), mean = -50, sd = 5)
r[,1:1000]<- NA
r[,3000:5005]<- NA

R_sum<- function(x){
  out<- c(x[1]+x[2],
          x[2]+x[3],
          x[3]+x[4],
          x[4]+x[5],
          x[5]+x[6],
          x[6]+x[7])
  return(out)
  }

v3x3<- terra::focal(r, w=c(3,3), fun = R_sum, fillvalue=NA)
plot(v3x3)
```
![R_v3x3](https://user-images.githubusercontent.com/28163862/152232690-fe032cd1-9f51-409d-8141-c63fd041929c.png)


```
v25x25<- terra::focal(r, w=c(25,25), fun = R_sum, fillvalue=NA)
plot(v25x25)
```
![R_v25x25](https://user-images.githubusercontent.com/28163862/152232699-287a78ee-66ba-468a-9ffc-f3d658d635a9.png)

**Comment by rhijmans** [comment] 2022-02-06 02:37
Thanks, that is very helpful. Can you try again with the dev version?

**Comment by ailich** [comment] 2022-02-06 03:46
@rhijmans, I installed from github and ran the examples above and the issues still persists. Some variation in the striping and blocking patterns compared to what is plotted, but very similar.

**Comment by ailich** [comment] 2022-02-08 18:43
@rhijmans, I can also get this to break using a larger raster with a single layer output. To keep the size of the output in number of elements consistent, I made the input raster have 6 times as many cells and applied a function that only returns a single element (as opposed to 6). The function returns the value of the focal cell so it should return back the original raster. I've filled in the raster with values represented by their index so maybe it can help shed some light on where/why things are getting jumbled. I've found that the outputs differ by run, introduce `NA` values, place values in the incorrect locations however the overall pattern of low values at the top and high values at the bottom is retained. 

```
library(terra)
library(Rcpp)

#Should retuen center calue of window (aka the original raster)
cppFunction( 
  'NumericVector fcenter(NumericVector x, size_t ni, size_t nw) {
		NumericVector out(ni);
		int c_idx = (nw-1)/2; //index of focal pixel
		for (size_t i=0; i<ni; i++) {
		  size_t start = i*nw;
		  size_t end = start+nw-1;
		  NumericVector xw = x[Rcpp::Range(start,end)]; //Current window of values
			out[i] = xw[c_idx];
		}		
		return out;
	}'
)


r<- rast(nrow = 5005*3, ncol= 4893*2, crs="EPSG:32620", extent= c(164751.39956803, 409401.39956803, 4833140.707, 5083390.707))
values(r) <- 1:ncell(r)

c25 <- terra::focalCpp(r, w=25, fun=fcenter)
c25_v2 <- terra::focalCpp(r, w=25, fun=fcenter)

freq(r==c25)
#        layer   value   count
# [1,]     1     0       64637317
# [2,]     1     1       679

freq(r==c25_v2)
#        layer  value    count
# [1,]     1     0       123383904
# [2,]     1     1       433

freq(c25==c25_v2)
#       layer   value   count
# [1,]     1     0      54486355
# [2,]     1     1      1217

out<- c(r,c25, c25_v2)
names(out)<- c("original", "v1", "v2")
plot(out)
```
![cfun_plot](https://user-images.githubusercontent.com/28163862/153054291-674e7cc8-a98b-4afc-908b-64646dade2bd.png)

**Comment by rhijmans** [comment] 2022-02-12 23:02
I believe that, at long last, this has now been fixed! Please let me know....

**Comment by rhijmans** [comment] 2022-02-13 06:29
That is a different matter. This happens because the values are very large numbers, and because they are saved to a FLT4S temp file some precision is lost.

```
library(terra)
library(Rcpp)

# more efficient version
cppFunction(   
  'NumericVector fcenter(NumericVector x, size_t ni, size_t nw) {
		NumericVector out(ni);
		size_t idx = (nw-1)/2;
		for (size_t i=0; i<ni; i++) {
			out[i] = x[idx];
			idx += nw;
		}		
		return out;
	}'
)

r <- rast(nrow = 2070, ncol= 9786, crs="EPSG:32620", extent= c(164751, 409401, 4833140, 5083390))
values(r) <- 1:ncell(r)

# small differences
z1 <- focalCpp(r, w=25, fun=fcenter)
z1-r
#min value   :    -1 
#max value   :     1 
 
## write double precision instead 
terraOptions(datatype="FLT8S")
z2 <- focalCpp(r, w=25, fun=fcenter)
z2-r
                                                  
z2-r
#min value   :     0 
#max value   :     0 
``` 

Arguably the default should be `FLT8S`; but that doubles the size of the temp files.

**Comment by ailich** [comment] 2022-02-13 16:42
@rhijmans, thanks! This is fixed then! I am a bit confused about the precision issue though as I'd expect that to just be small differences far out in the decimal places, but I was getting plus or minus 8, so if you could just elaborate/clarify a bit on why that would occur I'd appreciate it. That being said using `FLT8S` I do get the same raster back. Thanks!

**Comment by rhijmans** [comment] 2022-02-13 18:28
In practice this is often about the decimal places, but the limitation is the number of digits that can be stored. That also applies to large numbers. A 4 byte float has 24 bits to store the number and eight for the exponent.

2^24 = 16777216  and larger integers are approximated. You see that here

z1[1715, 4005:4018]
#      lyr.1
#1  16777209
#2  16777210
#3  16777211
#4  16777212
#5  16777213
#6  16777214
#7  16777215
#8  16777216
#9  16777216
#10 16777218
#11 16777220
#12 16777220
#13 16777220
#14 16777222

**Closed** 2022-02-13 18:57 UTC
