### ISSUE TITLE
terra::zonal slower than raster::zonal when using many small zones

### ISSUE THREAD

**Issue by dvictori** [rspatial/terra#595] opened 2022-03-30 01:34 UTC
I'm in the process of substituting `raster` for `terra` and I noticed a drop in performance during some zonal stats procedures. I have a very detailed zone map (Brazilian municipalities). So I did some benchmarks and noticed that `terra::zonal` is faster than `raster::zonal` when dealing with a zone map with larger areas. But if we use a zone map with many small zones, `terra::zonal` becomes slower than `raster::zonal`.

Here goes a reprex:
``` r
# Testing zonal stats performance for raster and terra packages
# checking with 2 zone maps:
#    2000z: 2000 zones and 500 pixels on each zone
#    500z :  500 zones and 2000 pixels on each zone
library(raster)
#> Loading required package: sp
library(terra)
#> terra 1.5.21
library(microbenchmark)
library(ggplot2)
#> 
#> Attaching package: 'ggplot2'
#> The following object is masked from 'package:terra':
#> 
#>     arrow
bm <- microbenchmark(
  raster_2000z = {
    r_raster <- raster::raster(ncols = 1000, nrows = 1000)
    raster::values(r_raster) <-
      runif(ncell(r_raster)) * 1:ncell(r_raster)
    z_raster <- r_raster
    raster::values(z_raster) <- rep(1:2000, each = 500)
    raster::zonal(r_raster, z_raster, 'mean')
  },
  raster_500z = {
    r_raster <- raster::raster(ncols = 1000, nrows = 1000)
    raster::values(r_raster) <-
      runif(ncell(r_raster)) * 1:ncell(r_raster)
    z_raster <- r_raster
    raster::values(z_raster) <- rep(1:500, each = 2000)
    raster::zonal(r_raster, z_raster, 'mean')
  },
  terra_2000z = {
    r_terra <- terra::rast(ncols = 1000, nrows = 1000)
    terra::values(r_terra) <-
      runif(ncell(r_terra)) * 1:ncell(r_terra)
    z_terra <- r_terra
    terra::values(z_terra) <- rep(1:2000, each = 500)
    terra::zonal(r_terra, z_terra, 'mean')
  },
  terra_500z = {
    r_terra <- terra::rast(ncols = 1000, nrows = 1000)
    terra::values(r_terra) <-
      runif(ncell(r_terra)) * 1:ncell(r_terra)
    z_terra <- r_terra
    terra::values(z_terra) <- rep(1:500, each = 2000)
    terra::zonal(r_terra, z_terra, 'mean')
  },
  times = 30
)

# package raster shows similar performance for both zone maps
# package terra has better performance for 500z but is worse than raster for 2000z
bm
#> Unit: milliseconds
#>          expr       min        lq      mean    median        uq       max neval
#>  raster_2000z  792.6422  827.2366  884.0668  855.6052  930.6744 1237.4621    30
#>   raster_500z  759.9533  767.5437  840.4829  810.3877  930.0720 1080.5016    30
#>   terra_2000z 1103.4486 1143.4249 1164.8886 1162.5878 1180.0189 1329.4962    30
#>    terra_500z  345.8691  359.4164  364.0558  362.7096  368.4917  379.3469    30
#>  cld
#>   b 
#>   b 
#>    c
#>  a
autoplot(bm)
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/UcrPA34.png)

``` r
sessionInfo()
#> R version 4.1.0 (2021-05-18)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.4 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
#> 
#> locale:
#>  [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=pt_BR.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] ggplot2_3.3.5        microbenchmark_1.4.9 terra_1.5-21        
#> [4] raster_3.5-15        sp_1.4-6            
#> 
#> loaded via a namespace (and not attached):
#>  [1] zoo_1.8-9        tidyselect_1.1.1 xfun_0.29        purrr_0.3.4     
#>  [5] splines_4.1.0    lattice_0.20-44  colorspace_2.0-2 vctrs_0.3.8     
#>  [9] generics_0.1.2   htmltools_0.5.2  yaml_2.2.2       survival_3.2-11 
#> [13] utf8_1.2.2       rlang_1.0.1      pillar_1.7.0     glue_1.6.1      
#> [17] withr_2.4.3      DBI_1.1.2        multcomp_1.4-18  lifecycle_1.0.1 
#> [21] stringr_1.4.0    munsell_0.5.0    gtable_0.3.0     mvtnorm_1.1-3   
#> [25] codetools_0.2-18 evaluate_0.14    knitr_1.37       fastmap_1.1.0   
#> [29] fansi_1.0.2      highr_0.9        TH.data_1.1-0    Rcpp_1.0.8      
#> [33] scales_1.1.1     farver_2.1.0     fs_1.5.2         digest_0.6.29   
#> [37] stringi_1.7.6    dplyr_1.0.8      grid_4.1.0       rgdal_1.5-29    
#> [41] cli_3.2.0        tools_4.1.0      sandwich_3.0-1   magrittr_2.0.2  
#> [45] tibble_3.1.6     crayon_1.5.0     pkgconfig_2.0.3  MASS_7.3-54     
#> [49] Matrix_1.3-4     ellipsis_0.3.2   reprex_2.0.1     assertthat_0.2.1
#> [53] rmarkdown_2.11   rstudioapi_0.13  R6_2.5.1         compiler_4.1.0
```

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment] 2022-04-01 23:55
duplicate of #533

**Comment by rhijmans** [comment] 2022-07-04 22:31
This has now been fixed. Thanks for the useful benchmark. You can see that "terra" is much faster now:

```
library(raster)
library(terra)
library(microbenchmark)
library(ggplot2)

r_raster <- raster(ncols = 1000, nrows = 1000)
values(r_raster) <- runif(ncell(r_raster))
z_raster1 <- setValues(r_raster, rep(1:2000, each = 500))
z_raster2 <- setValues(r_raster, rep(1:500, each = 2000))

r_terra <- rast(r_raster)
z_terra1 <- rast(z_raster1)
z_terra2 <- rast(z_raster2)


bm <- microbenchmark(
  raster_2000z = zonal(r_raster, z_raster1, 'mean'),
  raster_500z = zonal(r_raster, z_raster2, 'mean'),
  terra_old_2000z = zonal(r_terra, z_terra1, 'mean', old=TRUE), #old=TRUE is for testing, and will be removed
  terra_old_500z = zonal(r_terra, z_terra2, 'mean', old=TRUE),
  terra_new_2000z = zonal(r_terra, z_terra1, 'mean'),
  terra_new_500z = zonal(r_terra, z_terra2, 'mean'),
  times = 30
)

autoplot(bm)
```

![zonal](https://user-images.githubusercontent.com/11481397/177222116-92038234-f88d-46db-872a-f9e356a953a1.png)

**Closed by rhijmans** 2022-07-04 22:31 UTC
