### ISSUE TITLE
```writeRaster()``` in terra returns unexpected min and max values when using ```terra::rast()``` for .grd

### ISSUE THREAD

**Issue by bpfree** [rspatial/terra#963] opened 2023-01-03 20:04 UTC
I noticed that when I use terra to write a raster as a GRD value, when I pull in the exported raster the min and max values are unexpectedly large (e.g., -3.68e-19, 3,68e19, -3.402e+38, etc.). After noticing this, I tried to set the values using ```NAflag``` within ```terra::writeRaster()```, but that still produced similar results. I was able to get back to the correct values after using ```terra::classify()``` on the exported .grd file from ```terra::writeRaster``` data.

When similar data are created and exported using ```raster::raster()``` instead of ```terra::rast()```, the value ranges are the same as the original raster before using ```raster::writeRaster()```.

For instance, when comparing the data in one of the attached scripts, these are the values I get:

```
# Load data
## Import data exported from terra::writeRaster
bathymetry_terra <- terra::rast(paste(terra_dir, "bathymetry_terra.grd", sep = "/"))
bathymetry_terra
### min value   : -3.689349e+19
### max value   :  3.689349e+19

slope_terra <- terra::rast(paste(terra_dir, "slope_terra.grd", sep = "/"))
slope_terra
### min value   : -3.402561e+38
### max value   :  3.401994e+38

#####################################

## import data from terra::writeRaster and then reclassify
### Somehow reclassifying minimum also changes the maximum values -- become the range that the data should be
bathymetry_terra_reclass <- terra::rast(paste(terra_dir, "bathymetry_terra.grd", sep = "/")) %>%
  # reclassify any values below expected minimum to be NA
  terra::classify(cbind(terra::minmax(.)[1,], -250, NA))
bathymetry_terra_reclass
### min value   : -224.569778
### max value   : 7.388319 

slope_terra_reclass <- terra::rast(paste(terra_dir, "slope_terra.grd", sep = "/")) %>%
  # reclassify any values below expected minimum to be NA
  terra::classify(cbind(terra::minmax(.)[1,], -0.001, NA))
slope_terra_reclass
### min value   : 0.00000
### max value   : 35.16794

#####################################

bathymetry_raster <- raster::raster(paste(raster_dir, "bathymetry_raster.grd", sep = "/"))
bathymetry_raster
### values     : -192.8781, 8  (min, max)

slope_raster <- raster::raster(paste(raster_dir, "slope_raster.grd", sep = "/"))
slope_raster
### values     : 0, 33.95526  (min, max)
```

Sorry if I missed something that explains why terra produces these results. I went through open and closed issues but could not find anyone else who has encountered this issue. The closest thing I could find was [this](https://stackoverflow.com/questions/72474683/discrepancy-between-writeraster-of-raster-and-terra-package), and one of the answers did seem to suggest that my approach with ```classify``` is needed. I have not tried other data formats other than .grd, but I cannot imagine why ```terra()``` would produce the correct results like ```raster()``` does in a different format.

I have attached three scripts in an R Project and the associated data in the [zipped folder](https://github.com/rspatial/terra/files/10339387/terra_raster_comparison.zip). I could not share the bathymetry dataset as they were too large, but they are publicly available [here](https://www.ngdc.noaa.gov/thredds/fileServer/crm/crm_vol5.nc). If they are moved into the a_raw_data directory, the scripts should work fine.

Below are the results from sessionInfo():
```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9         compiler_4.2.0     pillar_1.8.1       class_7.3-20       tools_4.2.0        jsonlite_1.8.4    
 [7] lifecycle_1.0.3    tibble_3.1.8       lattice_0.20-45    pkgconfig_2.0.3    rlang_1.0.6        DBI_1.1.3         
[13] cli_3.5.0          rstudioapi_0.14    crul_1.3           curl_4.3.3         rgdal_1.6-3        e1071_1.7-12      
[19] terra_1.6-49       dplyr_1.0.10       stringr_1.5.0      raster_3.6-11      generics_0.1.3     vctrs_0.5.1       
[25] geojsonlint_0.4.0  classInt_0.4-8     grid_4.2.0         tidyselect_1.2.0   jsonvalidate_1.3.2 httpcode_0.3.0    
[31] glue_1.6.2         sf_1.0-9           R6_2.5.1           fansi_1.0.3        sp_1.5-1           tidyr_1.2.1       
[37] purrr_1.0.0        magrittr_2.0.3     rmapshaper_0.4.6   codetools_0.2-18   units_0.8-1        assertthat_0.2.1  
[43] V8_4.2.2           KernSmooth_2.23-20 utf8_1.2.2         proxy_0.4-27       stringi_1.7.8
```

**Comment by rhijmans** [comment] 2023-01-03 20:38
Can you create a minimal self-contained example that shows this? That is, use data generated in memory or with a file that ships with R. For example: 

```
library(terra)
r <- rast(system.file("ex/elev.tif", package="terra"))
```
or 

```
x <- rast(ncol=2, nrow=2, vals = c(1:3, NA))
```

**Comment by bpfree** [comment] 2023-01-03 20:54
Sure I will try to reproduce it with an example. My guess though it is has to do with NA values outside of a study area that terra is filling with the unexpected minimum and maximum values.

Reading, exporting, and rereading the elevation.tif does not reproduce the situation that I encountered. That returned the expected results.

**Comment by rhijmans** [comment] 2023-01-05 21:35
I can download and read the file like this 

```
url <- "https://www.ngdc.noaa.gov/thredds/fileServer/crm/crm_vol5.nc"
f <- basename(url)
if (!file.exists(f)) {
	options(timeout=1000)
	download.file(url, f, mode="wb")
}

library(terra)
r <- rast(f)
```

Can you show what to do next to create the problem you are reporting?

**Comment by rhijmans** [comment] 2023-01-13 21:38
Closing because I cannot reproduce this.

**Closed by rhijmans** 2023-01-13 21:38 UTC
