### ISSUE TITLE
 *** caught segfault ***: address (nil), cause 'memory not mapped'

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#740] opened 2022-08-02 23:57 UTC
While executing a loop for cropping hundreds of multi-layer NetCDF files using a polygon defined with a `SpatVector` object, I got the following error message (at 91% of the loop):

```
*** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .External(list(name = "CppMethod__invoke_notvoid", address = <point
er: 0x555fc39ea820>,     dll = list(name = "Rcpp", path = "/usr/local/l
ib/R/site-library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, han
dle = <pointer: 0x555fc44ce490>,         info = <pointer: 0x555fc310167
0>), numParameters = -1L),     <pointer: 0x555fc78dd810>, <pointer: 0x5
55fc78e2810>, .pointer,     ...)
 2: x@ptr$crop(y@ptr, snap[1], opt)
 3: .local(x, y, ...)
 4: terra::crop(x = lx, y = y, snap = snap)
 5: terra::crop(x = lx, y = y, snap = snap)
 6: FUN(X[[i]], ...)
 7: lapply(X[Split[[i]]], FUN, ...)
 8: pblapply(X = X, FUN = FUN, ..., cl = cl)
 9: pbapply::pbsapply(X = 1:nfiles, FUN = .maskFile, files = files,    
 nfiles = nfiles, y = y, y.ext = y.ext, touches = touches,     lsubds =
 subds, rotate = rotate, crs = crs, snap = snap,     suffix.out = suffi
x.out, fname.out = fname.out, format = format,     NAflag = NAflag, ove
rwrite = overwrite, zname = zname, prec = prec,     compression = compr
ession, longname = longname, unit = unit)
10: mycrop.character(x = drty.in, y = mask, prefix.in = prefix.in,    
 suffix.in = suffix.in, prefix.out = prefix.out, suffix.out = suffix.ou
t,     fname.length = fname.length, drty.out = drty.out)
11: mycrop(x = drty.in, y = mask, prefix.in = prefix.in, suffix.in = s
uffix.in,     prefix.out = prefix.out, suffix.out = suffix.out, fname.l
ength = fname.length,     drty.out = drty.out)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

Any idea what might be causing this error?

The output of my `sessionInfo()` is:

```
sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20.3

Matrix products: default
BLAS/LAPACK: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_CL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] hydroRTS_0.5-6 terra_1.6-3
```

**Comment by rhijmans** [comment] 2022-08-03 10:35
Hard to say from this. I have added some stronger safeguards against an empty SpatVector, but I do not think that is the issue. 
This could be related to your use of `pbapply::pbsapply`, especially if you are using a parallel processing backend. Can you reproduce this error? Does it occur when you run this sequentially?

**Comment by hzambran** [comment] 2022-08-03 13:47
Thank you very much for your response.

In fact, I could not prepare a reproducible example, but I tried the following:

1) removing the use of `pbapply::pbsapply`, but I got the same error.

2) replacing the parallel processing by a **sequential loop**, but the same error happened. However, this time I tried the same sequential loop with 7 other datasets with similar characteristics as the one triggering the error. None of the the other datasets triggered that  error.

I identified the first file triggering the error, and then I tried a sequential loop from that file onwards. I got the following error:

```
[Reading  file: chirpsv2-2019-04-EPSG4326.nc. 1/39 (2.56%) ... ]

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x5586d8b970e0>,     dll = list(name = "Rcpp", path = "/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x5586d964ced0>,         info = <pointer: 0x5586d9346550>), numParameters = -1L),     <pointer: 0x5586dca57ce0>, <pointer: 0x5586dca5cd40>, .pointer,     ...)
 2: x@ptr$crop(y@ptr, snap[1], opt)
 3: .local(x, y, ...)
 4: terra::crop(x = x, y = lmask, snap = "out")
 5: terra::crop(x = x, y = lmask, snap = "out")
 6: cropSingleMLfile(x = drty.in, part = 1, lmask = lmask, prefix.in = prefix.in,     suffix.in = suffix.in, drty.out = drty.out, prefix.out = prefix.out,     suffix.out = suffix.out, multiplier = 1)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

When I read the file `chirpsv2-2019-04-EPSG4326.nc` (30 layers) I see its information:

```
class       : SpatRaster 
dimensions  : 666, 211, 30  (nrow, ncol, nlyr)
resolution  : 0.05, 0.05  (x, y)
extent      : -76.3, -65.75, -50, -16.7  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : chirpsv2-2019-04-EPSG4326.nc 
varname     : var_1 
names       : var_1_1, var_1_2, var_1_3, var_1_4, var_1_5, var_1_6, ... 
time        : 2019-04-01 to 2019-04-30 UTC 
```

and I'm able to plot all the 30 layers individually.

The `lmask` object used for cropping is the following:

```
 lmask
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 1, 1  (geometries, attributes)
 extent      : -75.73, -66.41, -55.99, -17.49  (xmin, xmax, ymin, ymax)
 source      : mask_Chile_plus_simplified_EPSG4326.shp
 coord. ref. : lon/lat WGS 84 (EPSG:4326) 
 names       : cr2metv2-A
 type        :      <int>
 values      :          1
```

Any idea about the cause of the error?

**Comment by rhijmans** [comment] 2022-08-03 18:29
That suggests that `chirpsv2-2019-04-EPSG4326.nc` is corrupted. Can you share / point to that file?

**Comment by hzambran** [comment] 2022-08-04 19:39
Here is the file:

[chirpsv2-2019-04-EPSG4326.nc.zip](https://github.com/rspatial/terra/files/9262739/chirpsv2-2019-04-EPSG4326.nc.zip)

I don't know where is the error, because when I plot the previous file I can see all the layers...

In fact, to solve the issue I removed all the files belonging to year 2019, and download them again (many GeoTiff files), and pack them in NetCDF files.

**Comment by kadyb** [comment] 2022-08-04 23:02
Your polygon has lower "ymin" value in extent than the raster and it looks like this doesn't work for `snap = "out"` argument. So the problem is probably with the `crop()` function. See:

```r
r = rast("chirpsv2-2019-04-EPSG4326.nc")
ext(r)

e = ext(-75.73, -66.41, -55.99, -17.49)
e = as.polygons(e, crs = "epsg:4326")
# fails
rr = crop(r, e, snap = "out") # but `snap = "in"` and `snap = "near"` works

e = ext(-75.73, -66.41, -55.99, -17.49)
e[3] = -50 # make ymin in `e` higher than in `r`
e = as.polygons(e, crs = "epsg:4326")
rr = crop(r, e, snap = "out") # now it works
```

**Comment by rhijmans** [comment] 2022-08-05 13:16
Fixed now. Thanks a million @kadyb for pointing to the cause of this bug.

**Closed** 2022-08-05 13:15 UTC

**Comment by hzambran** [comment] 2022-08-05 23:27
Thank to you both for your help and to @kadyb for point out to this bug, now fixed. 

What is weird is that I carried out the same operation over more than 100  .nc files with the same spatial extension of `chirpsv2-2019-04-EPSG4326.nc` and with the `same` polygon, and only that triggered an error.

Anyway thanks a lot to you both.

**Comment by rhijmans** [comment] 2022-08-06 05:56
Perhaps because the extent of the other files was slightly different?  This file has 

``` 
ext(r)
# SpatExtent : -76.29999845487, -65.749998297675, -50.00000149, -16.70000099383 (xmin, xmax, ymin, ymax)
```

I imagine that the others may have

```
# SpatExtent : -76.30, -65.75, -50.00, -16.70 (xmin, xmax, ymin, ymax)
```
