### ISSUE TITLE
Artifact when predicting in parallel

### ISSUE THREAD

**Issue by joheisig** [rspatial/terra#1038] opened 2023-02-28 08:34 UTC
Hi there,
first, thank you for constantly improving the package, really helpful!

I recently discovered undesired artifacts when predicting a simple linear model onto a multi-layer SpatRaster in parallel with `terra::predict(SR, linear_mod, cores = 4)`. They appear as if they come from the mosaicing after parallel processing. The issue resolved when only using a single core. See a sample of the results below (4 cores vs 1 core). Can one specify a resampling method when predicting in parallel to avoid this behavior? 
Thanks!

<img src="https://user-images.githubusercontent.com/28398169/221795358-4038c158-930c-4475-8cd9-d958fe4f3cc7.png"  width="40%" > <img src="https://user-images.githubusercontent.com/28398169/221795411-a0635f35-933c-476e-a5b4-1b5e684d5b9e.png"  width="40%" >

**Comment by rhijmans** [comment] 2023-02-28 19:38
I cannot think of a way that `predict` could do that. There is no resampling, and all the computations are local (cell by cell). 
The values are not split in tiles like this when using multiple cores.  And the examples in `?predict` do not show this artifact when using multiple cores. 

Of course, I can see that there *is* an issue. But what can the underlying cause be? I wondered about the file structure and format of the input data (the predictor variables). Perhaps it is tiled? But I do not see how that might interact with using multiple cores.  

Any chance you can make a reproducible example that I can inspect? You could share it privately if need be.

**Comment by joheisig** [comment] 2023-03-02 12:06
Thanks for your thoughts. The predictors are pretty big (45x33 k cells, 70 individual files), but not tiled. I do not see the artifact when using `plot`, but mainly because of the automatic resampling before the plot is shown. Took me  a while to spot it in a gis. So far I was not able to reproduce this behavior with a much simpler setup. If I manage to do so I will report and share an example.

**Comment by rhijmans** [comment] 2023-03-05 03:40
You could crop to a small extent to show these bands with `plot`. It would be great to have an example if you can find one. I will close the issue for now, because there is really nothing to go on for me.

**Closed by rhijmans** 2023-03-05 03:40 UTC
