### ISSUE TITLE
Can only open one NetCDF file per R session

### ISSUE THREAD

**Issue by RRTogunov** [rspatial/terra#221] opened 2021-05-21 18:58 UTC
When reading NetCDF files, only the contents of the first file are read - all subsequent imports are identical to the first.
For example, using the following ice drift data,
[weekly_drift.zip](https://github.com/rspatial/terra/files/6524530/weekly_drift.zip)
`library(terra);`
`plot(rast("ice drift 1979.nc"));`
`plot(rast("ice drift 1980.nc"))
`
the plots for 1980 are identical to 1979.
However, if you shut down and restart R studio session, and import the same files, the 1979 plots are identical to 1980
`
library(terra);`
`plot(rast("ice drift 1980.nc"));`
`plot(rast("ice drift 1979.nc"))
`

**Comment by rhijmans** [comment] 2021-05-21 19:40
When I run your code, I see clearly different data, with RStudio, and without it. 

```
library(terra);
x <- rast("ice drift 1979.nc");
y <- rast("ice drift 1980.nc")
x
#class       : SpatRaster 
#dimensions  : 361, 361, 156  (nrow, ncol, nlyr)
#resolution  : 25067.53, 25067.53  (x, y)
#extent      : -4524688, 4524688, -4524688, 4524688  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#sources     : ice drift 1979.nc:u  (52 layers) 
#              ice drift 1979.nc:v  (52 layers) 
#              ice drift 1979.nc:number_of_observations  (52 layers) 
#varnames    : u (sea_ice_x_velocity) 
#              v (sea_ice_y_velocity) 
#              number_of_observations (Number of daily Ice Motion fields in average) 
#names       :    u_1,    u_2,    u_3,    u_4,    u_5,    u_6, ... 
#unit        : cm / s, cm / s, cm / s, cm / s, cm / s, cm / s, ... 
#time        : 1979-01-01 12:00:00 to 1979-12-24 12:00:00 

y
#class       : SpatRaster 
#dimensions  : 361, 361, 156  (nrow, ncol, nlyr)
#resolution  : 25067.53, 25067.53  (x, y)
#extent      : -4524688, 4524688, -4524688, 4524688  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#sources     : ice drift 1980.nc:u  (52 layers) 
#              ice drift 1980.nc:v  (52 layers) 
#              ice drift 1980.nc:number_of_observations  (52 layers) 
#varnames    : u (sea_ice_x_velocity) 
#              v (sea_ice_y_velocity) 
#              number_of_observations (Number of daily Ice Motion fields in average) 
#names       :    u_1,    u_2,    u_3,    u_4,    u_5,    u_6, ... 
#unit        : cm / s, cm / s, cm / s, cm / s, cm / s, cm / s, ... 
#time        : 1980-01-01 12:00:00 to 1980-12-23 12:00:00 

par(mfrow=c(1,2))

plot(x, 1)
plot(y, 1)
```
![test](https://user-images.githubusercontent.com/11481397/119190023-a6d3e300-ba31-11eb-9ce0-c0d62e1ae025.png)


I am guessing that there is probably something else you do that causes confusion.

**Comment by jkjkjij22** [comment] 2021-05-21 20:33
I found the source of the issue:
It works as intended when the NetCDF files are stored on the C:/ drive. However, when they are stored in a local google drive folder (downloaded and available offline), I get the original problem. 
I have had a similar problem using the `ncdf4` package, which I could solved by explicitly closing the NC file using `nc_close` after extracting the data before opening the next file.

**Comment by rhijmans** [comment] 2021-05-21 22:43
Are you saying that if you run the code below `x` and `y` are the same? I can't understand how that would be possible. 

```
x <- rast("ice drift 1979.nc");
y <- rast("ice drift 1980.nc")
```

**Comment by jkjkjij22** [comment] 2021-05-21 23:40
Yes, if the files are in a local Google Drive folder, that is correct. 
Note: in the picture below, the working directory is in Google Drive.
![terrabug](https://user-images.githubusercontent.com/20913113/119207458-20c89400-ba53-11eb-8959-944bf74093cf.png)

**Comment by rhijmans** [comment] 2021-05-22 00:16
That would suggest that in the Google drive folder these files actually are the same (only have different names).  I cannot think of another plausible explanation. Does it matter in which order you open the files? If you first open the 1980 file, do you still get the 1979 values? If you copy these two files to a different location are they then different?  There has got to be something else going on that has nothing to do with R or `terra`

**Comment by jkjkjij22** [comment] 2021-05-22 00:58
To ensure the files in Google Drive are identical, I ran the following code. I first import using `terra` from C, then move the files to G:\, and import with `terra` and `raster`, then I check the identity (different when imported from C or using `raster`, but identical if importing from G using `terra`)
```
# Improt from C:/
library(terra)
setwd("C:/")
a <- rast("ice drift 1979.nc")
b <- rast("ice drift 1980.nc")

# move files to "G:/My Drive"
file.copy("ice drift 1979.nc", "G:/My Drive", overwrite = T)
file.copy("ice drift 1980.nc", "G:/My Drive", overwrite = T)

# import from G:/My Drive
setwd("G:/My Drive")
x.terra <- rast("ice drift 1979.nc")
y.terra <- rast("ice drift 1980.nc")
# load same files with raster
library(raster)
x.raster <- raster("ice drift 1979.nc")
y.raster <- raster("ice drift 1980.nc")

# compare rasters 
identical(values(a$u_1),  # terra rasters from C
          values(b$u_1))
identical(values(x.terra), # terra rasters from G
          values(y.terra))
identical(values(x.raster), # raster rasters from G
          values(y.raster))
# plot
par(mfrow = c(3,2))
plot(a, 1)
plot(b, 1)
plot(x.terra, 1)
plot(y.terra, 1)
plot(x.raster, 1)
plot(y.raster, 1)
```
And yes, it appears that the values are always taken from the first file imported - switching the two years (switch all "1979" and "1980" in the code) results in `terra` importing only 1980 data from google drive.
 
![terra bug 80_79](https://user-images.githubusercontent.com/20913113/119209818-bcf79880-ba5d-11eb-888d-7ba7996936e6.png)
![terra bug 79_80](https://user-images.githubusercontent.com/20913113/119209819-bd902f00-ba5d-11eb-8e3e-1badce4c33d6.png)
![terrabug_2](https://user-images.githubusercontent.com/20913113/119209820-bd902f00-ba5d-11eb-92e7-be6469bd8016.png)

**Comment by rhijmans** [comment] 2021-05-22 01:28
Thanks that is very clear and helpful. Albeit extraordinarily puzzling. Can you also show what this returns?

```
sources(x.terra)
sources(y.terra)
```

**Comment by jkjkjij22** [comment] 2021-05-22 04:42
The sources do correspond to the correct files. 
![image](https://user-images.githubusercontent.com/20913113/119214659-54201880-ba7d-11eb-965a-bbb529b8e409.png)

**Comment by rhijmans** [comment] 2021-05-26 18:29
Can you see if this happens with other file formats, such as GeoTIFF as well, for example like this?

```
library(terra)
library(raster)
setwd("C:/")
a <- rast("ice drift 1979.nc")
b <- rast("ice drift 1980.nc")
a <- writeRaster(a, "ice drift 1979.tif")
b <- writeRaster(b, "ice drift 1980.tif")
file.copy("ice drift 1979.tif", "G:/My Drive", overwrite = T)
file.copy("ice drift 1980.tif", "G:/My Drive", overwrite = T)

setwd("G:/My Drive")
x.terra <- rast("ice drift 1979.tif")
y.terra <- rast("ice drift 1980.tif")
x.raster <- raster("ice drift 1979.nc")
y.raster <- raster("ice drift 1980.nc")

identical(values(a), values(b))
identical(values(x.terra), values(y.terra))
identical(values(x.raster), values(y.raster))
```

**Comment by jkjkjij22** [comment] 2021-05-26 18:46
It does not happen with GeoTIFFs. 

```
library(terra)
library(raster)
setwd("C:/") 
a.nc <- rast("ice drift 1979.nc")
b.nc <- rast("ice drift 1980.nc")
a.tif <- writeRaster(a.nc, "ice drift 1979.tif", overwrite = T)
b.tif <- writeRaster(b.nc, "ice drift 1980.tif", overwrite = T)
file.copy("ice drift 1979.tif", "G:/My Drive", overwrite = T)
file.copy("ice drift 1980.tif", "G:/My Drive", overwrite = T)

setwd("G:/My Drive")
x.terra.tif <- rast("ice drift 1979.tif")
y.terra.tif <- rast("ice drift 1980.tif")
x.terra.nc <- rast("ice drift 1979.nc")
y.terra.nc <- rast("ice drift 1980.nc")
x.raster <- raster("ice drift 1979.nc")
y.raster <- raster("ice drift 1980.nc")

identical(values(a.nc), values(b.nc))
identical(values(a.tif), values(b.tif))
identical(values(x.terra.tif), values(y.terra.tif))
identical(values(x.terra.nc), values(y.terra.nc))
identical(values(x.raster), values(y.raster))
```
The results show that the original NetCDFs were different, as were they when converted to GeoTIFF. The GeoTIFFs were still different when moved to G:/, however NetCDFs were the same after moved to G:/, but were the same when imported with `raster`
![image](https://user-images.githubusercontent.com/20913113/119714033-394ffa00-be17-11eb-85cc-6a29c410bdf6.png)

**Comment by rhijmans** [comment] 2021-11-21 05:04
This remains an unresolved mystery. Since there have not been any other reports, I am closing the issue.

**Closed by rhijmans** 2021-11-21 05:04 UTC
