### ISSUE TITLE
intersect( )  => Input geom 0 is INVALID: Self-intersection at or near poin....

### ISSUE THREAD

**Issue by hirscht** [rspatial/terra#471] opened 2022-01-07 14:14 UTC
I´m using intersect( ) for two SpatVector to find overlapping areas of two sets of polygons, when it comes to the follwing error:

**Input geom 0 is INVALID: Self-intersection at or near point 6.5 45.124653739612185 (6.5 45.124653739612185177)
MULTIPOLYGON ((( ............   .........    .........)))
Error: TopologyException: Input geom 0 is invalid: Self-intersection at 6.5 45.124653739612185**

Zooming in towards the mentioned point, I can see two holes in one of the polygons, joining at one of the corners, which must cause the problem of "self-intersection"

![stabmap80_corrmap0 4_zoom6 5-45_ERA5-msl_vs_MQ-Kaub_Rhein_1951-2020-01-lag01](https://user-images.githubusercontent.com/92745862/148553288-387876d5-aaa4-4b7e-afa7-08e8ed8e3215.png)

I could reproduce the bug using a self-made case with similar "joining holes" in one of the polygons:

![self-intersection](https://user-images.githubusercontent.com/92745862/148554396-bf22d30d-1a45-4025-af40-988dd82b9bcb.png)

terra::intersect(polygon1, polygon2 ) leading to =>

**Input geom 0 is INVALID: Self-intersection at or near point 0.30000000000000004 0.5 (0.30000000000000004441 0.5)
<A>
POLYGON ((0.0000000000000000 1.0000000000000000, 0.0000000000000000 0.0000000000000000, 1.0000000000000000 0.0000000000000000, 1.0000000000000000 1.0000000000000000, 0.0000000000000000 1.0000000000000000), (0.2000000000000000 0.6000000000000000, 0.2000000000000000 0.5000000000000000, 0.4000000000000000 0.5000000000000000, 0.4000000000000000 0.3999999999999999, 0.3000000000000000 0.3999999999999999, 0.3000000000000000 0.6000000000000000, 0.2000000000000000 0.6000000000000000))
</A>
Error: TopologyException: Input geom 0 is invalid: Self-intersection at 0.30000000000000004 0.5**

I have found a similiar issue: https://github.com/rspatial/terra/issues/28 where it was referred to as a raster issue.
I am using terra::patches and terra::as.polygons to create SpatVectors, which do have these "joining holes" and I´m getting the bug using terra:intersect. So, this seems to be a terra issue, to me.
Shouldn´t there be such "joining holes" in a SpatVector? This is, however, what I get using terra::patches + terra::as.polygons starting from a SpatRaster.
The only solution, I could find by now is to get rid of those holes withing my polygons using terra::fillHoles. This might cause some unwanted results in my case and wonder if there is another solution to this...?

**Comment by rhijmans** [comment] 2022-01-07 18:29
Thanks, that is a thorny issue. I need to think about how to fix this. But here is a full reproducible example

```
library(terra)
r <- rast(nrow=10, ncol=10, xmin=0, xmax=1, ymin=0, ymax=1, vals=1)
r[c(44,55)] <- NA
p1 <- as.polygons(r)
p2 <- vect("POLYGON ((0.8 1.5, 0.8 0.5, 1.5 0.5, 1.5 1.5, 0.8 1.5))")

i <- intersect(p1, p2)
#Error: TopologyException: Input geom 0 is invalid: Self-intersection at 0.40000000000000002 0.5

plot(rbind(p1, p2), col=rev(rainbow(2)), alpha=.25)
points(0.4, 0.5, cex=2, pch=20, col="red")
```

![selfintersect](https://user-images.githubusercontent.com/11481397/148589854-4d9f73d3-fab3-415e-bd20-aed8f00b48e9.png)

**Comment by edzer** [comment] 2022-01-07 20:55
> i <- intersect(p1, p2)

works fine for me (GEOS 3.10.1)

**Comment by rhijmans** [comment] 2022-01-07 21:00
@edzer thanks very much, I also see that now. For example on Ubuntu with the latest versions of  `ubuntugis-unstable`   which has GEOS 3.10.1. CRAN terra/windows has GEOS 3.9.0

**Comment by edzer** [comment] 2022-01-07 21:04
On lower versions, one could try to roundtrip `p1` through `sf::st_make_valid()`.

**Comment by rhijmans** [comment] 2022-01-07 22:10
Here are some comparisons. `terra` had a makeValid method using OGR (that uses GEOS perhaps?) but that wasn't exposed, I can't remember why, but I assume because it did not work. Now I have also added the GEOS 3.8 method, and that works (I am not sure why). The sf method loses the hole(s),  I am not sure why.

```
library(terra)
p2 <- vect("POLYGON ((0.8 1.5, 0.8 0.5, 1.5 0.5, 1.5 1.5, 0.8 1.5))")
r <- rast(nrow=10, ncol=10, xmin=0, xmax=1, ymin=0, ymax=1, vals=1)
r[c(44,55)] <- NA
p1 <- as.polygons(r)

# not exported OGR method
v1 <- p1
v1@ptr <- p1@ptr$make_valid()
# geos method 
v2 <- makeValid(p1)
geom(v1, TRUE)
#[1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.3 0.6, 0.3 0.5, 0.5 0.5, 0.5 0.4, 0.4 0.4, 0.4 0.6, 0.3 0.6))"
geom(v2, TRUE)
#[1] "POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1),(0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6, 0.3 0.5),(0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5, 0.4 0.4))" i <- intersect(v2, p2)
# no error 
``` 
(that is nice, but as.polygons() should not create this in the first place)

With `sf` something else happens

```
library(sf)
s1 <- st_as_sf(p1)
s2 <- st_make_valid(s1)
v3 <- vect(s2)
geom(v3, TRUE)
# "MULTIPOLYGON (((0.4 0.6, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.3 0.5, 0.3 0.6, 0.4 0.6)),((0 1, 0 0, 1 0, 1 1, 0 1)))"
``` 
Instead of holes, we now have overlapping polygons. And the intersection fails. I do not think that it is because of the terra->sf->terra translation.

**Comment by edzer** [comment] 2022-01-07 22:23
The whole intersection / overlay engine in GEOS was redesigned and reimplemented in GEOS 3.9.0 -> 3.9.1 -> 3.10.0; it was called "overlay-ng", see e.g. here: https://lists.osgeo.org/pipermail/geos-devel/2020-December/010003.html ; 3.9.0 still had serious problems.

> terra had a makeValid method using OGR (that uses GEOS perhaps?) but that wasn't exposed, I can't remember why, but I assume because it did not work.

There's a reason why rgeos and rgdal are two packages, and why sf calls all its geom ops from GEOS, not OGR: GEOS can only be linked _dynamically_ to GDAL. This means that for binary installs (macos, windows), GDAL is not linked to GEOS (as binary installs _only_ work for statically linked libraries). In that case, all OGR functions that should call to GEOS don't work. I am not 100% sure this is still the case on all platforms - @rsbivand can you confirm?

**Comment by rhijmans** [comment] 2022-01-07 23:34
I see that it also works with sf with current ubuntugis

```
library(sf)
#Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
s1 <- st_as_sf(p1)
s2 <- st_make_valid(s1)
v3 <- vect(s2)
geom(v3, TRUE)
#[1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.4 0.6, 0.4 0.5, 0.3 0.5, 0.3 0.6, 0.4 0.6),(0.5 0.5, 0.5 0.4, 0.4 0.4, 0.4 0.5, 0.5 0.5))"
``` 
The single hole is split in two making each hole valid.

But not on windows 
```
library(sf)
#Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
geom(v3, TRUE)
#[1] "MULTIPOLYGON (((0.4 0.6, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.3 0.5, 0.3 0.6, 0.4 0.6)),((0 1, 0 0, 1 0, 1 1, 0 1)))"
``` 
The hole is made another (and still invalid) polygon. That is somewhat mysterious because it works with terra-devel and GEOS 3.9.0 (probably because this is not the UCRT version)

```
gdal()
#   gdal    proj    geos 
#"3.2.1" "7.2.1" "3.9.0" 
```

**Comment by edzer** [comment] 2022-01-07 23:47
ring direction?

**Comment by rhijmans** [comment] 2022-01-08 03:37
@hirscht 

It appears that this problem does not occur with 

```
gdal()
    gdal     proj     geos
 "3.4.0"  "8.2.0" "3.10.1"
``` 

As the geometry created by `as.polygons` is valid. 

```
library(terra)
r <- rast(nrow=10, ncol=10, xmin=0, xmax=1, ymin=0, ymax=1, vals=1)
p <- as.polygons(r)
geom(p, TRUE)
r[c(44,55)] <- NA
p <- as.polygons(r)
geom(p, TRUE)
#[1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.3 0.6, 0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6),(0.4 0.5, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5))"
```

Note that there is one hull, with two holes.

But with older versions, even with

```
gdal()
#   gdal    proj    geos 
#"3.2.1" "7.2.1" "3.9.0" 
```
The geometry is invalid as there is only a single hole that self-intersects
```
geom(p, TRUE)
#[1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.3 0.6, 0.3 0.5, 0.5 0.5, 0.5 0.4, 0.4 0.4, 0.4 0.6, 0.3 0.6))"
```

But, this can be fixed with `makeValid` (if you have GEOS >= 3.8)

``` 
makeValid(p) |> geom(TRUE)
#[1] "POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1),(0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6, 0.3 0.5),(0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5, 0.4 0.4))"
```  

So, I am not going to fix this.

**Comment by rsbivand** [comment] 2022-01-08 12:26
I agree that the raster cells represented as polygons include an invalidity as seen by GEOS, and also see that different versions of GEOS respond differently. A further problem occurs in **sf** where the geographical coordinates are seen as such and go to **s2**, which leads to a different invalidity. I looked at GEOS 3.10.1 and 3.9.1 (also on macOS/Windows static-built CRAN binaries) without seeing a clear pattern, using **terra**, **sf** and **rgeos**. I also tried to look at the precision model used by GEOS without finding any clear picture.

**Comment by rhijmans** [comment] 2022-01-08 21:52
Below I show that it indeed matters whether the crs is `lonlat` or not. Roger says that **sf** uses **s2** instead (or perhaps in addition to), GEOS with `lonlat` data, and that would explain the discrepancy with terra.

```
library(terra)
library(sf)

f <- function(crs) {
	r <- rast(nrow=10, ncol=10, xmin=0, xmax=1, ymin=0, ymax=1, vals=1, crs=crs)
	r[c(44,55)] <- NA
	p <- as.polygons(r)
	s <- st_as_sf(p)
	sv <- st_make_valid(s)
	geom(vect(sv), TRUE)
}

# valid
f("+proj=utm +zone=1")
#[1] "POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1),(0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6, 0.3 0.5),(0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5, 0.4 0.4))"
 
# invalid
f("+proj=longlat")
#[1] "MULTIPOLYGON (((0.4 0.6, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.3 0.5, 0.3 0.6, 0.4 0.6)),((0 1, 0 0, 1 0, 1 1, 0 1)))"
```

**Closed by rhijmans** 2022-01-08 21:52 UTC

**Comment by edzer** [comment] 2022-01-09 10:31
Strange, I'm seeing
```r
library(terra)
# terra 1.5.8
library(sf)
# Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE

f <- function(crs) {
	r <- rast(nrow=10, ncol=10, xmin=0, xmax=1, ymin=0, ymax=1, vals=1, crs=crs)
	r[c(44,55)] <- NA
	p <- as.polygons(r)
	s <- st_as_sf(p)
	sv <- st_make_valid(s)
	geom(vect(sv), TRUE)
}

# valid
f("+proj=utm +zone=1")
# [1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.3 0.6, 0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6),(0.4 0.5, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5))"
 
# invalid?
f("+proj=longlat")
# [1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.4 0.6, 0.4 0.5, 0.3 0.5, 0.3 0.6, 0.4 0.6),(0.5 0.5, 0.5 0.4, 0.4 0.4, 0.4 0.5, 0.5 0.5))"
sessionInfo()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Ubuntu 20.04.3 LTS

# Matrix products: default
# BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
# LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

# locale:
#  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
#  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
#  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
#  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     

# other attached packages:
# [1] sf_1.0-6    terra_1.5-8

# loaded via a namespace (and not attached):
#  [1] Rcpp_1.0.7         magrittr_2.0.1     units_0.7-2        tidyselect_1.1.1  
#  [5] R6_2.5.1           rlang_0.4.12       fansi_0.5.0        s2_1.0.7          
#  [9] dplyr_1.0.7        wk_0.6.0           tools_4.1.2        grid_4.1.2        
# [13] KernSmooth_2.23-20 utf8_1.2.2         e1071_1.7-9        DBI_1.1.2         
# [17] ellipsis_0.3.2     class_7.3-19       assertthat_0.2.1   tibble_3.1.6      
# [21] lifecycle_1.0.1    crayon_1.4.2       purrr_0.3.4        vctrs_0.3.8       
# [25] codetools_0.2-18   glue_1.6.0         proxy_0.4-26       compiler_4.1.2    
# [29] pillar_1.6.4       generics_0.1.1     classInt_0.4-3     pkgconfig_2.0.3   

```

**Comment by rhijmans** [comment] 2022-01-09 21:55
I see that too. And I now see that on windows it depends. 

**R-current**

```
library(terra)
#terra 1.5.9
library(sf)
#Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
 
f("+proj=utm +zone=1")
#[1] "POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1),(0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6, 0.3 0.5),(0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5, 0.4 0.4))"
  
# invalid
f("+proj=longlat")
#[1] "MULTIPOLYGON (((0.4 0.6, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.3 0.5, 0.3 0.6, 0.4 0.6)),((0 1, 0 0, 1 0, 1 1, 0 1)))"
sf_use_s2(FALSE)
#Spherical geometry (s2) switched off
# valid!
f("+proj=longlat")
#[1] "POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1),(0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6, 0.3 0.5),(0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5, 0.4 0.4))"
 
sessionInfo()
#R version 4.1.2 (2021-11-01)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows 10 x64 (build 19043)

#Matrix products: default

#locale:
#[1] LC_COLLATE=English_United States.1252 
#[2] LC_CTYPE=English_United States.1252   
#[3] LC_MONETARY=English_United States.1252
#[4] LC_NUMERIC=C                          
#[5] LC_TIME=English_United States.1252    

#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     

#other attached packages:
#[1] sf_1.0-5    terra_1.5-9

#loaded via a namespace (and not attached):
# [1] Rcpp_1.0.7         magrittr_2.0.1     units_0.7-2        tidyselect_1.1.1  
# [5] R6_2.5.1           rlang_0.4.12       fansi_0.5.0        s2_1.0.7          
# [9] dplyr_1.0.7        wk_0.5.0           tools_4.1.2        grid_4.1.2        
#[13] KernSmooth_2.23-20 utf8_1.2.2         e1071_1.7-9        DBI_1.1.1         
#[17] ellipsis_0.3.2     class_7.3-19       tibble_3.1.6       lifecycle_1.0.1   
#[21] crayon_1.4.2       purrr_0.3.4        vctrs_0.3.8        codetools_0.2-18  
#[25] glue_1.5.1         proxy_0.4-26       compiler_4.1.2     pillar_1.6.4      
#[29] generics_0.1.1     classInt_0.4-3     pkgconfig_2.0.3   
``` 

**R-devel**

```
library(terra)
#terra 1.5.9
library(sf)
#Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1; sf_use_s2() is TRUE

# valid
f("+proj=utm +zone=1")
[1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.3 0.6, 0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6),(0.4 0.5, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5))"

# valid!
f("+proj=longlat")
[1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.4 0.6, 0.4 0.5, 0.3 0.5, 0.3 0.6, 0.4 0.6),(0.5 0.5, 0.5 0.4, 0.4 0.4, 0.4 0.5, 0.5 0.5))"
> sf_use_s2(FALSE)
Spherical geometry (s2) switched off
# also valid
f("+proj=longlat")
#[1] "POLYGON ((0 1, 0 0, 1 0, 1 1, 0 1),(0.3 0.6, 0.3 0.5, 0.4 0.5, 0.4 0.6, 0.3 0.6),(0.4 0.5, 0.4 0.4, 0.5 0.4, 0.5 0.5, 0.4 0.5))"
 
sessionInfo()
#R Under development (unstable) (2022-01-07 r81458 ucrt)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows 10 x64 (build 19043)

#Matrix products: default

#locale:
#[1] LC_COLLATE=English_United States.utf8 
#[2] LC_CTYPE=English_United States.utf8   
#[3] LC_MONETARY=English_United States.utf8
#[4] LC_NUMERIC=C                          
#[5] LC_TIME=English_United States.utf8    

#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     

#other attached packages:
#[1] sf_1.0-5    terra_1.5-9

#loaded via a namespace (and not attached):
# [1] compiler_4.2.0     magrittr_2.0.1     class_7.3-19      
# [4] s2_1.0.7           tools_4.2.0        DBI_1.1.2         
# [7] units_0.7-2        proxy_0.4-26       wk_0.6.0          
#[10] Rcpp_1.0.7         KernSmooth_2.23-20 codetools_0.2-18  
#[13] grid_4.2.0         e1071_1.7-9        classInt_0.4-3    
```

The ordering of the nodes changes, but in all cases you get 1 hull and 2 holes.
