### ISSUE TITLE
union(): CBR: result (after common-bits addition) is INVALID

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#929] opened 2022-12-03 08:15 UTC
Not sure if this is a bug or not, I report it for your consideration.
I suspect this is rather a problem with my input data, but the error does not
help to guess how to fix it. (Data available upon request):

With terra:
```
> packageVersion("terra")
[1] ‘1.6.47’
> v <- union(PL_Treat,PL_AOI2019 )
CBR: result (after common-bits addition) is INVALID: Self-intersection at or near point 443580.36162694963 4623078.2778014429 (443580.36162694962695 4623078.2778014428914)
<A>
GEOMETRYCOLLECTION (LINESTRING (443560.1210843484732322 4623087.1564081441611052, 443557.0253673116094433 4623084.6798345148563385), LINESTRING (443557.5411170461447909 4623108.5973586402833462, 443557.3594061445328407 4623107.9140911269932985), LINESTRING (

```
and a very long list of LINESTRING coordinates (while the result v looks correct).
How could I correct this error?

sf does not complain:
```
> library("sf")
Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.2.1; sf_use_s2() is TRUE
> packageVersion("sf")
[1] ‘1.0.7’
> PL_AOI2019sf <- st_as_sf(PL_AOI2019)
> PL_Treatsf   <- st_as_sf(PL_Treat)
> vsf <- st_union(PL_Treatsf,PL_AOI2019sf )
Warning message:
attribute variables are assumed to be spatially constant throughout all geometries 

```
but the vsf result does not look correct (or sf has a different concept of union).
I am not a heavy user of sf, though, and I'm confused by the warning. I will be asking
in the sf forums in parallel and will report back.

**Comment by dbaston** [comment] 2022-12-06 01:19
This error is emitted by GEOS. You shouldn't see if it you have GEOS >= 3.9, so either `terra` is loading a different version of GEOS from `sf`, or `terra` is indeed using GEOS 3.9 and there is a problem in GEOS. Can you share your data?

**Comment by rhijmans** [comment] 2023-02-03 03:33
Closing because I cannot reproduce this.

**Closed by rhijmans** 2023-02-03 03:33 UTC
