### ISSUE TITLE
caught segfault - 'memory not mapped' error

### ISSUE THREAD

**Issue by ENIAC-6** [rspatial/terra#961] opened 2022-12-29 23:16 UTC
I am trying to write a vrt to disk on an HPC. A smaller example generated from a project with 14 tiles works great, but on a larger example with thousands of tiles, I get a "caught segfault " error. 
 
Looking at https://stackoverflow.com/questions/49190251/caught-segfault-memory-not-mapped-error-in-r led me to wonder whether there was an issue with my packages, and so I reinstalled everything, but get the same error. I was wondering whether there is any other combination of R and packages versions that would avoid this error?

I have available to me R/3.6.3  R/4.1.1  R/4.1.3(default)  R/4.2.0.

gdal/3.0.4 proj/6.2.1 geos/3.8.1 are they only versions currently available to me on the HPC, but I can request others.

#--------------------------------------------------------------------------------------------
vrt that works:
class       : SpatRaster 
dimensions  : 16000, 4000, 1  (nrow, ncol, nlyr)
resolution  : 0.5, 0.5  (x, y)
extent      : 281000, 283000, 4954000, 4962000  (xmin, xmax, ymin, ymax)
coord. ref. : NAD83(2011) / UTM zone 13N (EPSG:6342) 
source      : spat_omHbKp0IyMscddg_384289.vrt 
name        : spat_omHbKp0IyMscddg_384289 

vrt that doesn't write to disk:
class       : SpatRaster 
dimensions  : 120000, 415000, 1  (nrow, ncol, nlyr)
resolution  : 3, 3  (x, y)
extent      : 1995000, 3240000, 1470000, 1830000  (xmin, xmax, ymin, ymax)
coord. ref. : NAD83(2011) / Colorado Central (ftUS) 
source      : spat_TrqEBkWP0pc7ElF_426181.vrt 
name        : spat_TrqEBkWP0pc7ElF_426181 

#--------------------------------------------------------------------------------------------

I'm currently using: `module load R/3.6.3 gdal/3.0.4 proj/6.2.1 geos/3.8.1`

> sessinonInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /cm/shared/apps/openblas/0.2.20/lib/libopenblas-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] proj4_1.0-12  rgeos_0.6-1   raster_3.6-11 pbdMPI_0.4-6  Rcpp_1.0.9   
[6] sf_1.0-9      terra_1.6-47  rgdal_1.6-3   sp_1.4-5     

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1     units_0.8-1        float_0.3-0        tidyselect_1.1.0  
 [5] lattice_0.20-38    R6_2.5.0           rlang_0.4.10       fansi_0.4.2       
 [9] rlecuyer_0.3-5     dplyr_1.0.5        tools_3.6.3        grid_3.6.3   
[13] utf8_1.2.1         KernSmooth_2.23-16 e1071_1.7-6        DBI_1.1.3         
[17] ellipsis_0.3.1     class_7.3-15       tibble_3.1.0       lifecycle_1.0.0   
[21] crayon_1.4.1       purrr_0.3.4        vctrs_0.3.7        codetools_0.2-16  
[25] glue_1.4.2         proxy_0.4-25       pillar_1.5.1       compiler_3.6.3    
[29] generics_0.1.0     classInt_0.4-8     pkgconfig_2.0.3   

#--------------------------------------------------------------------------------------------
Error:

 *** caught segfault ***
address 0x2abb64808000, cause 'memory not mapped'

Traceback:
 1: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x1ce42c0>,     dll = list(name = "Rcpp", path = "/home/username/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x2793ea0>,         info = <pointer: 0x659500>), numParameters = -1L), <pointer: 0x2905e70>,     <pointer: 0x28b3a80>, .pointer, ...)
 2: x@ptr$writeRaster(opt)
 3: .local(x, filename, ...)
 4: terra::writeRaster(x = virtual_mosaic_dems, filename = dat$RasterOut[array_task_id])
 5: terra::writeRaster(x = virtual_mosaic_dems, filename = dat$RasterOut[array_task_id])
An irrecoverable exception occurred. R is aborting now ...
srun: error: ml-0007: task 0: Segmentation fault

#--------------------------------------------------------------------------------------------

My overall goal is to 1) create one mosaic rasters from all of the individual DEM tiles for various 3DEP projects at once with job arrays, and 2) split the vrts into smaller (overlapping tiles) to parallel process slope, aspect, etc. (using all terrain() options) and then recombine them and write those DEM derivatives to disk as well.

For goal 1) my code is:

```
# get array task ID
args = commandArgs(trailingOnly=TRUE) # pass $SLURM_ARRAY_TASK_ID as command line arg
array_task_id <- as.integer(args[1])

dat <- read.table("raster_projects.csv", header=TRUE, sep=",", stringsAsFactors=FALSE)

if ((array_task_id > 0) & (array_task_id <= nrow(dat))) {
    outdir <- dat$TiffDirectory[array_task_id]
    
    library(terra)
    
    # Create list of absolute paths of DEM tiles
    list_dems <-  base::list.files(path = outdir, pattern = '*.tif', full.names = TRUE)
    
    # Generate mosaic raster dataset
    
    # Create virtual mosaic of DEM tiles
    virtual_mosaic_dems <- terra::vrt(x = list_dems)
    
    # Write virtual mosaic to disk to create a mosaic raster dataset
    terra::writeRaster(x = virtual_mosaic_dems, filename = dat$RasterOut[array_task_id])

} else {
    cat("There is no processing task for array task ID ", array_task_id, "!\n", sep="")
}
```

#--------------------------------------------------------------------------------------------

The example DEMs were downloaded with:
wget --secure-protocol TLSv1_2 --reject jpg  --no-clobber --recursive --continue --no-parent --no-host-directories --cut-dirs 6 --wait=1 --random-wait https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/OPR/Projects/CO_Central_and_WesternCO_2016_A16/CO_Central_Western_2016/TIFF/

**Comment by rhijmans** [comment] 2023-01-20 19:44
If it works for a small example but not for the larger problem then it is not likely to be an issue related to the general configuration (such as mismatches of versions). The best I can suggest is to split the task into regions so that you do not have to deal with as many files at the same time.

**Comment by rhijmans** [comment] 2023-02-03 03:37
Closing because I cannot reproduce this problem.

**Closed by rhijmans** 2023-02-03 03:37 UTC
